"""initial migration

Revision ID: 2666a787ad06
Revises:
Create Date: 2024-09-29 20:25:43.966991

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2666a787ad06"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
