"""create sku table

Revision ID: bedbf9fc4585
Revises: 2666a787ad06
Create Date: 2024-09-30 02:31:02.364843

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bedbf9fc4585"
down_revision: Union[str, None] = "2666a787ad06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sku",
        sa.Column("uuid", sa.UUID(), nullable=False, comment="id товара в нашей бд"),
        sa.Column("marketplace_id", sa.Integer(), nullable=False, comment="id маркетплейса"),
        sa.Column(
            "product_id",
            sa.BigInteger(),
            nullable=False,
            comment="id товара в маркетплейсе",
        ),
        sa.Column("title", sa.Text(), nullable=True, comment="название товара"),
        sa.Column("description", sa.Text(), nullable=True, comment="описание товара"),
        sa.Column("brand", sa.Text(), nullable=True),
        sa.Column("seller_id", sa.Integer(), nullable=True),
        sa.Column("seller_name", sa.Text(), nullable=True),
        sa.Column("first_image_url", sa.Text(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column(
            "category_lvl_1",
            sa.Text(),
            nullable=True,
            comment="Первая часть категории товара",
        ),
        sa.Column(
            "category_lvl_2",
            sa.Text(),
            nullable=True,
            comment="Вторая часть категории товара",
        ),
        sa.Column(
            "category_lvl_3",
            sa.Text(),
            nullable=True,
            comment="Третья часть категории товара",
        ),
        sa.Column(
            "category_remaining",
            sa.Text(),
            nullable=True,
            comment="Остаток категории товара",
        ),
        sa.Column("features", sa.JSON(), nullable=True, comment="Характеристики товара"),
        sa.Column(
            "rating_count",
            sa.Integer(),
            nullable=True,
            comment="Кол-во отзывов о товаре",
        ),
        sa.Column("rating_value", sa.Double(), nullable=True, comment="Рейтинг товара (0-5)"),
        sa.Column("price_before_discounts", sa.Float(), nullable=True),
        sa.Column("discount", sa.Double(), nullable=True),
        sa.Column("price_after_discounts", sa.Float(), nullable=True),
        sa.Column("bonuses", sa.Integer(), nullable=True),
        sa.Column("sales", sa.Integer(), nullable=True),
        sa.Column(
            "inserted_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("currency", sa.Text(), nullable=True),
        sa.Column(
            "barcode",
            sa.Numeric(precision=60, scale=0),
            nullable=True,
            comment="Штрихкод",
        ),
        sa.Column("similar_sku", sa.ARRAY(sa.UUID()), nullable=True),
        sa.PrimaryKeyConstraint("uuid", name=op.f("sku_pkey")),
        schema="public",
    )
    op.create_index(op.f("public_sku_brand_idx"), "sku", ["brand"], unique=False, schema="public")
    op.create_index("sku_brand_index", "sku", ["brand"], unique=False, schema="public")
    op.create_index(
        "sku_marketplace_id_sku_id_uindex",
        "sku",
        ["marketplace_id", "product_id"],
        unique=True,
        schema="public",
    )
    op.create_index("sku_uuid_uindex", "sku", ["uuid"], unique=True, schema="public")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("sku_uuid_uindex", table_name="sku", schema="public")
    op.drop_index("sku_marketplace_id_sku_id_uindex", table_name="sku", schema="public")
    op.drop_index("sku_brand_index", table_name="sku", schema="public")
    op.drop_index(op.f("public_sku_brand_idx"), table_name="sku", schema="public")
    op.drop_table("sku", schema="public")
    # ### end Alembic commands ###
